# Generated by Django 6.0.7 on 2026-08-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pengaduan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=150)),
                ("telepon", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "kategori",
                    models.CharField(
                        choices=[
                            ("saran", "Saran"),
                            ("masukan", "Masukan"),
                            ("fasilitas", "Fasilitas"),
                            ("kebersihan", "Kebersihan"),
                            ("keamanan", "Keamanan"),
                            ("lainnya", "Lainnya"),
                        ],
                        max_length=20,
                    ),
                ),
                ("pesan", models.TextField()),
                (
                    "lampiran",
                    models.FileField(
                        blank=True, null=True, upload_to="pengaduan/lampiran/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("baru", "Baru"),
                            ("diproses", "Diproses"),
                            ("selesai", "Selesai"),
                        ],
                        default="baru",
                        max_length=20,
                    ),
                ),
                ("dibuat_pada", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Pengaduan",
                "verbose_name_plural": "Pengaduan & Masukan",
                "ordering": ["-dibuat_pada"],
            },
        ),
    ]
