# Generated by Django 6.0.7 on 2026-08-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaint", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pengaduan",
            name="kategori_lainnya",
            field=models.CharField(
                blank=True,
                help_text="Diisi hanya jika kategori = 'Lainnya'",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="pengaduan",
            name="nama",
            field=models.CharField(blank=True, default="Anonim", max_length=150),
        ),
    ]
