# Generated by Django 6.0.7 on 2026-07-31 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProfilUPTD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sambutan_judul",
                    models.CharField(
                        default="Mewujudkan Pasar Segiri sebagai Pusat Ekonomi Rakyat yang Nyaman dan Modern",
                        help_text="Judul/tagline sambutan pimpinan",
                        max_length=200,
                    ),
                ),
                (
                    "sambutan_isi",
                    models.TextField(help_text="Isi lengkap sambutan pimpinan"),
                ),
                ("nama_kepala", models.CharField(max_length=100)),
                (
                    "jabatan_kepala",
                    models.CharField(
                        default="Kepala UPTD Pasar Segiri", max_length=150
                    ),
                ),
                (
                    "foto_kepala",
                    models.ImageField(blank=True, null=True, upload_to="profil/"),
                ),
                (
                    "visi",
                    models.TextField(help_text="Kalimat visi, tanpa perlu tanda kutip"),
                ),
                (
                    "struktur_organisasi",
                    models.ImageField(
                        blank=True,
                        help_text="Gambar bagan struktur organisasi",
                        null=True,
                        upload_to="profil/",
                    ),
                ),
                ("alamat", models.TextField()),
                (
                    "google_maps_embed_url",
                    models.URLField(
                        help_text="URL src dari iframe embed Google Maps (Share > Embed a map)"
                    ),
                ),
                (
                    "google_maps_link",
                    models.URLField(
                        help_text="Link biasa Google Maps (buat tombol 'Buka di Google Maps')"
                    ),
                ),
                (
                    "jam_senin_kamis",
                    models.CharField(default="07.30 - 14.30", max_length=50),
                ),
                ("jam_jumat", models.CharField(default="07.30 - 11.30", max_length=50)),
                ("jam_sabtu", models.CharField(default="07.30 - 13.00", max_length=50)),
                ("jam_minggu", models.CharField(default="Libur", max_length=50)),
            ],
            options={
                "verbose_name": "Profil UPTD",
                "verbose_name_plural": "Profil UPTD",
            },
        ),
        migrations.CreateModel(
            name="MisiUPTD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("urutan", models.PositiveSmallIntegerField(default=1)),
                ("isi", models.CharField(max_length=300)),
                (
                    "profil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="misi_list",
                        to="core.profiluptd",
                    ),
                ),
            ],
            options={
                "verbose_name": "Misi",
                "verbose_name_plural": "Misi",
                "ordering": ["urutan"],
            },
        ),
    ]
