# Generated by Django 6.0.7 on 2026-07-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profiluptd",
            name="google_maps_embed_url",
            field=models.URLField(
                help_text="URL src dari iframe embed Google Maps (Share > Embed a map)",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="profiluptd",
            name="google_maps_link",
            field=models.URLField(
                help_text="Link biasa Google Maps (buat tombol 'Buka di Google Maps')",
                max_length=500,
            ),
        ),
    ]
