# Generated by Django 6.0.7 on 2026-08-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_profiluptd_google_maps_embed_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(help_text='Judul singkat foto', max_length=200)),
                ('kategori', models.CharField(choices=[('kebersamaan', 'Kebersamaan'), ('kegiatan', 'Kegiatan')], max_length=20)),
                ('foto', models.ImageField(upload_to='galeri/')),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('tanggal', models.DateField()),
            ],
            options={
                'verbose_name': 'Galeri',
                'verbose_name_plural': 'Galeri',
                'ordering': ['-tanggal'],
            },
        ),
    ]
