# Generated by Django 6.0.7 on 2026-08-04 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_galeri'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(help_text='Judul Banner (misal: HUT RI ke-81 / Pengelolaan Profesional)', max_length=200)),
                ('deskripsi', models.TextField(blank=True, help_text='Deskripsi singkat banner', null=True)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='hero_banners/')),
                ('teks_tombol', models.CharField(blank=True, help_text='Contoh: Lihat Unit Pasar / Selengkapnya', max_length=50, null=True)),
                ('link_tombol', models.CharField(blank=True, help_text='Link tujuan (contoh: /market/ atau #unit-pasar)', max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Centang untuk menampilkan banner di carousel beranda')),
                ('urutan', models.PositiveIntegerField(default=0, help_text='Urutan tampil banner (makin kecil makin depan)')),
            ],
            options={
                'verbose_name': 'Hero Banner',
                'verbose_name_plural': 'Hero Banners',
                'ordering': ['urutan', '-id'],
            },
        ),
    ]
