# Generated by Django 6.0.7 on 2026-08-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_herobanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herobanner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='judul',
            field=models.CharField(help_text='Judul Banner', max_length=200),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='link_tombol',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='teks_tombol',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='urutan',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
