# Generated by Django 6.0.7 on 2026-08-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_herobanner_is_active_alter_herobanner_judul_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBannerUtama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(default='Mewujudkan Pasar Segiri sebagai Pusat Ekonomi Rakyat', help_text='Judul Banner Utama (Slide 1 Beranda)', max_length=200)),
                ('deskripsi', models.TextField(blank=True, default='Pengelolaan pasar tradisional yang bersih, aman, dan nyaman untuk warga Samarinda.', help_text='Deskripsi singkat banner utama', null=True)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='hero_banners/')),
                ('teks_tombol', models.CharField(blank=True, default='Lihat Unit Pasar', max_length=50, null=True)),
                ('link_tombol', models.CharField(blank=True, default='/pasar/', max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Hero Banner Utama',
                'verbose_name_plural': 'Hero Banner Utama',
            },
        ),
        migrations.DeleteModel(
            name='HeroBanner',
        ),
    ]
