# Generated by Django 6.0.7 on 2026-08-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_herobannerutama_delete_herobanner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herobannerutama',
            name='deskripsi',
        ),
        migrations.RemoveField(
            model_name='herobannerutama',
            name='judul',
        ),
        migrations.RemoveField(
            model_name='herobannerutama',
            name='link_tombol',
        ),
        migrations.RemoveField(
            model_name='herobannerutama',
            name='teks_tombol',
        ),
        migrations.AlterField(
            model_name='herobannerutama',
            name='gambar',
            field=models.ImageField(blank=True, help_text='Gambar Banner Utama (Slide 1 Beranda)', null=True, upload_to='hero_banners/'),
        ),
    ]
