# Generated by Django 6.0.7 on 2026-07-31 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anggota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150)),
                ('jabatan', models.CharField(help_text='Contoh: KEPALA UPTD / KOORDINATOR KEBERSIHAN', max_length=150)),
                ('nip', models.CharField(blank=True, help_text='Kosongkan jika staf biasa', max_length=50, null=True, verbose_name='NIP')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='anggota/')),
                ('kategori', models.CharField(choices=[('pimpinan', 'Pimpinan'), ('staf', 'Staf & Koordinator Lapangan')], default='staf', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('urutan', models.PositiveIntegerField(default=1, help_text='Urutan posisi tampilan')),
            ],
            options={
                'verbose_name': 'Anggota',
                'verbose_name_plural': 'Daftar Anggota',
                'ordering': ['urutan'],
            },
        ),
    ]
