# Generated by Django 6.0.7 on 2026-07-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anggota',
            options={'ordering': ['urutan']},
        ),
        migrations.AddField(
            model_name='anggota',
            name='masa_jabatan',
            field=models.CharField(blank=True, help_text='Contoh: 2022 - Sekarang', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='anggota',
            name='uraian_tugas',
            field=models.TextField(blank=True, help_text='Penjelasan detail uraian tugas anggota', null=True),
        ),
        migrations.AlterField(
            model_name='anggota',
            name='jabatan',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='anggota',
            name='kategori',
            field=models.CharField(choices=[('pimpinan', 'Pimpinan'), ('staf', 'Staf & Koordinator Lapangan')], max_length=20),
        ),
        migrations.AlterField(
            model_name='anggota',
            name='nama',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='anggota',
            name='nip',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='anggota',
            name='urutan',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
