# Generated by Django 6.0.7 on 2026-08-02 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "market",
            "0002_pasar_ekosistem_pedagang_pasar_google_maps_embed_url_and_more",
        ),
        ("membership", "0002_alter_anggota_options_anggota_masa_jabatan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="anggota",
            name="pasar",
            field=models.ForeignKey(
                blank=True,
                help_text="Isi jika anggota ini adalah pengelola unit pasar tertentu. Kosongkan jika anggota tingkat dinas/UPTD pusat.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="anggota",
                to="market.pasar",
            ),
        ),
    ]
