# Generated by Django 6.0.7 on 2026-08-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_anggota_pasar'),
    ]

    operations = [
        migrations.AddField(
            model_name='anggota',
            name='sambutan_singkat',
            field=models.TextField(blank=True, help_text='Kata sambutan / deskripsi singkat (Khusus Kategori Pimpinan)', null=True),
        ),
    ]
