# Generated by Django 6.0.7 on 2026-08-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pasar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=150)),
                ("slug", models.SlugField(blank=True, max_length=170, unique=True)),
                ("alamat", models.TextField()),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="market/foto/"),
                ),
                (
                    "jumlah_pedagang",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Update manual sesuai data rekap terbaru (bulanan/tahunan). Merepresentasikan pedagang TERDAFTAR, bukan status kehadiran aktif harian.",
                    ),
                ),
                (
                    "kelas",
                    models.CharField(
                        blank=True,
                        choices=[("A", "Tipe A"), ("B", "Tipe B"), ("C", "Tipe C")],
                        max_length=1,
                    ),
                ),
                (
                    "jam_operasional",
                    models.CharField(
                        blank=True, default="06.00 - 18.00 WITA", max_length=100
                    ),
                ),
                (
                    "deskripsi",
                    models.TextField(
                        blank=True,
                        help_text="Opsional, paragraf penjelasan singkat tentang pasar ini.",
                    ),
                ),
                (
                    "urutan",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Urutan tampil di halaman daftar (kecil di depan).",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unit Pasar",
                "verbose_name_plural": "Unit Pasar",
                "ordering": ["urutan", "nama"],
            },
        ),
    ]
