# Generated by Django 6.0.7 on 2026-08-02 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pasar",
            name="ekosistem_pedagang",
            field=models.TextField(
                blank=True,
                help_text="Paragraf 'Ekosistem Pedagang' pada halaman detail.",
            ),
        ),
        migrations.AddField(
            model_name="pasar",
            name="google_maps_embed_url",
            field=models.URLField(
                blank=True,
                help_text="URL embed dari Google Maps (Share > Embed a map > src iframe).",
            ),
        ),
        migrations.AddField(
            model_name="pasar",
            name="google_maps_link",
            field=models.URLField(
                blank=True,
                help_text="Link 'Buka Google Maps' (link biasa, bukan embed).",
            ),
        ),
        migrations.AddField(
            model_name="pasar",
            name="sejarah_fungsi",
            field=models.TextField(
                blank=True, help_text="Paragraf 'Sejarah & Fungsi' pada halaman detail."
            ),
        ),
        migrations.AddField(
            model_name="pasar",
            name="struktur_organisasi_image",
            field=models.ImageField(
                blank=True,
                help_text="Gambar bagan struktur organisasi unit pasar ini.",
                null=True,
                upload_to="market/struktur/",
            ),
        ),
        migrations.AddField(
            model_name="pasar",
            name="video_youtube_url",
            field=models.URLField(
                blank=True,
                help_text="Tempel URL video YouTube (contoh: https://www.youtube.com/watch?v=XXXXXXXXXXX). Kosongkan jika belum ada video profil pasar ini.",
            ),
        ),
        migrations.CreateModel(
            name="DokumenResmi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("judul", models.CharField(max_length=150)),
                ("file", models.FileField(upload_to="market/dokumen/")),
                ("urutan", models.PositiveSmallIntegerField(default=0)),
                ("diunggah_pada", models.DateTimeField(auto_now_add=True)),
                (
                    "pasar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dokumen_resmi",
                        to="market.pasar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dokumen Resmi",
                "verbose_name_plural": "Dokumen Resmi",
                "ordering": ["urutan", "-diunggah_pada"],
            },
        ),
        migrations.CreateModel(
            name="FotoAktivitasPasar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gambar", models.ImageField(upload_to="market/aktivitas/")),
                ("keterangan", models.CharField(blank=True, max_length=150)),
                ("urutan", models.PositiveSmallIntegerField(default=0)),
                (
                    "pasar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="foto_aktivitas",
                        to="market.pasar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Foto Aktivitas Pasar",
                "verbose_name_plural": "Foto Aktivitas Pasar",
                "ordering": ["urutan", "id"],
            },
        ),
        migrations.CreateModel(
            name="KomoditasUnggulan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=100)),
                ("urutan", models.PositiveSmallIntegerField(default=0)),
                (
                    "pasar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="komoditas_unggulan",
                        to="market.pasar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Komoditas Unggulan",
                "verbose_name_plural": "Komoditas Unggulan",
                "ordering": ["urutan", "id"],
            },
        ),
        migrations.CreateModel(
            name="SaranaFasilitas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=100)),
                ("urutan", models.PositiveSmallIntegerField(default=0)),
                (
                    "pasar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sarana_fasilitas",
                        to="market.pasar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sarana & Fasilitas",
                "verbose_name_plural": "Sarana & Fasilitas",
                "ordering": ["urutan", "id"],
            },
        ),
    ]
