# Generated by Django 6.0.7 on 2026-08-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "market",
            "0002_pasar_ekosistem_pedagang_pasar_google_maps_embed_url_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="pasar",
            name="google_maps_embed_url",
            field=models.URLField(
                blank=True,
                help_text="URL embed dari Google Maps (Share > Embed a map > src iframe).",
                max_length=500,
            ),
        ),
    ]
