# Generated by Django 6.0.7 on 2026-08-03 06:39

import django.core.validators
import market.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0003_alter_pasar_google_maps_embed_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pasar",
            name="video_youtube_url",
        ),
        migrations.AddField(
            model_name="pasar",
            name="video_profil",
            field=models.FileField(
                blank=True,
                help_text="Upload video profil pasar ini (format MP4/WebM, maks 45MB). Kompres dulu ke H.264 720p pakai HandBrake/ffmpeg sebelum upload. Kosongkan jika belum ada video.",
                null=True,
                upload_to="market/video/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4", "webm"]
                    ),
                    market.models.validate_video_size,
                ],
            ),
        ),
        migrations.AddField(
            model_name="pasar",
            name="video_thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Foto poster/thumbnail video (ditampilkan sebelum user klik play). Jika kosong, akan pakai foto utama pasar sebagai fallback.",
                null=True,
                upload_to="market/video_thumbnail/",
            ),
        ),
    ]
