# Generated by Django 6.0.7 on 2026-09-11 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_remove_pasar_video_youtube_url_pasar_video_profil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasar',
            name='video_profil',
            field=models.CharField(blank=True, help_text='ID atau URL Video YouTube (Contoh: https://youtu.be/znNhAQzOCz0 atau znNhAQzOCz0). Kosongkan jika belum ada video.', max_length=255, null=True),
        ),
    ]
