# Generated by Django 6.0.7 on 2026-09-11 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pasar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('alamat', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='market/foto/')),
                ('jumlah_pedagang', models.PositiveIntegerField(default=0)),
                ('kelas', models.CharField(max_length=50)),
                ('jam_operasional', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('urutan', models.IntegerField(default=0)),
                ('video_profil', models.CharField(blank=True, help_text='ID atau URL Video YouTube', max_length=100, null=True)),
                ('video_thumbnail', models.ImageField(blank=True, null=True, upload_to='market/video_thumbs/')),
                ('sejarah_fungsi', models.TextField(blank=True, null=True)),
                ('ekosistem_pedagang', models.TextField(blank=True, null=True)),
                ('google_maps_embed_url', models.URLField(blank=True, max_length=500, null=True)),
                ('google_maps_link', models.URLField(blank=True, max_length=500, null=True)),
                ('struktur_organisasi_image', models.ImageField(blank=True, null=True, upload_to='market/struktur/')),
            ],
        ),
    ]
